spring.application.name=SKILL_6


# Server port
server.port=8080

# Show detailed error messages (useful for development)
server.error.include-message=always

# Logging level
logging.level.org.springframework=INFO